apiVersion : apps/v1
kind: Deployment
metadata:
  name: tester
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tester
  template:
    metadata:
      labels:
        app: tester
    spec:
      containers:
        - name: tester
          image: "eldarrin/main-log-test:latest"
          imagePullPolicy: Always
          env:
            - name: PRODUCTION
              value: "true"