apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: role-binding-dev
  namespace: dev
subjects:
  - kind: ServiceAccount
    name: svc-acct
    namespace: dev
roleRef:
  kind: Role
  name: read-only
  apiGroup: rbac.authorization.k8s.io