apiVersion : apps/v1
kind: Deployment
metadata:
  name: test-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-runner
  template:
    metadata:
      labels:
        app: test-runner
    spec:
      containers:
        - name: test-runner
          image: "eldarrin/testrunner:latest"
          imagePullPolicy: Always
          env:
            - name: RUNNER_NAME
              value: "main"
            - name: RUNNER_REPO
              value: "eldarrin/runbook-gitfarm"
            - name: DISABLE_AUTO_UPDATE
              value: "true"
            - name: EPHEMERAL
              value: "true"
            - name: LABELS
              value: "main"
            - name: RUNNER_TOKEN
              value: "token"
