name: RunBook

on:
  workflow_dispatch:

jobs:
  runbook:

    environment: development

    runs-on: ["self-hosted", "Windows", "x64"]

    steps:
      - name: powershell
        run: |
          $cmdOutput = kubectl get pods --namespace ${{ secrets.NAMESPACE }} -l app=tester -o jsonpath='{.items[0].metadata.name}'
          echo $cmdOutput
          kubectl logs --namespace ${{ secrets.NAMESPACE }} $cmdOutput
        shell: powershell

  runbook-prod:

    environment: production

    runs-on: ["self-hosted", "Windows", "x64"]

    steps:
      - name: script
        run: |
          $cmdOutput = kubectl get pods --namespace ${{ secrets.NAMESPACE }} -l app=tester -o jsonpath='{.items[0].metadata.name}'
          echo $cmdOutput
          kubectl logs --namespace ${{ secrets.NAMESPACE }} $cmdOutput
        shell: powershell
