name: RunBook

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  runbook:

    environment: development

    runs-on: ["self-hosted", "Windows", "x64"]

    steps:
      - name: powershell
        run: |
          $cmdOutput = kubectl get pods --namespace ${{ secrets.NAMESPACE }} -l app=tester -o jsonpath='{.items[0].metadata.name}'
          echo $cmdOutput
          kubectl logs --namespace ${{ secrets.NAMESPACE }} $cmdOutput > test.log
        shell: powershell

      - name: Create Issue From File
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: An example issue
          content-filepath: test.log
          labels: |
            report
            automated issue

  runbook-prod:

    environment: production

    runs-on: ["self-hosted", "Windows", "x64"]

    steps:
      - name: script
        run: |
          $cmdOutput = kubectl get pods --namespace ${{ secrets.NAMESPACE }} -l app=tester -o jsonpath='{.items[0].metadata.name}'
          echo $cmdOutput
          kubectl logs --namespace ${{ secrets.NAMESPACE }} $cmdOutput > prod.log
        shell: powershell

      - name: Create Issue From File
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: An production issue
          content-filepath: prod.log
          labels: |
            report
            bug