name: RunBook

on:
  workflow_dispatch:

jobs:
  runbook:

    environment: development

    runs-on: ["self-hosted", "Windows", "x64"]

    steps:
      - name: powershell
        run: |
          set POD_NAME=$(kubectl get pods --namespace dev -l app=tester -o jsonpath='{.items[0].metadata.name}')
          echo $POD_NAME
        shell: powershell

  runbook-prod:

    environment: production

    runs-on: ["self-hosted", "Windows", "x64"]

    steps:
      - name: script
        run: |
          set POD_NAME=$(kubectl get pods --namespace dev -l app=tester -o jsonpath='{.items[0].metadata.name}')
          echo $POD_NAME
        shell: powershell
